"""add applications table

Revision ID: 05ca0c5104e9
Revises: 946de6469907
Create Date: 2026-08-29 14:42:29.477926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05ca0c5104e9'
down_revision: Union[str, Sequence[str], None] = '946de6469907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_board_applications',
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='Identifier of the candidate who submitted this application'),
    sa.Column('job_id', sa.UUID(), nullable=False, comment='Identifier of the job this application targets'),
    sa.Column('cv_url', sa.String(length=2048), nullable=False, comment='S3 URL (or presigned URL reference) of the uploaded CV'),
    sa.Column('status', sa.Enum('SUBMITTED', 'REVIEWING', 'ACCEPTED', 'REJECTED', name='application_status_enum'), nullable=False, comment='Lifecycle status of the application'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['candidate_id'], ['job_board_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_board_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_applications_candidate_id_job_id')
    )
    op.create_index('ix_applications_candidate_id_job_id', 'job_board_applications', ['candidate_id', 'job_id'], unique=False)
    op.create_index('ix_applications_job_id_status', 'job_board_applications', ['job_id', 'status'], unique=False)
    op.alter_column('job_board_jobs', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               comment='Full-text search vector, auto-derived from title + description',
               existing_comment='Full-text search vector, title weighted above description',
               existing_nullable=True,
               existing_server_default=sa.Computed('(setweight(to_tsvector(\'english\'::regconfig, (COALESCE(title, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, COALESCE(description, \'\'::text)), \'B\'::"char"))', persisted=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_board_jobs', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               comment='Full-text search vector, title weighted above description',
               existing_comment='Full-text search vector, auto-derived from title + description',
               existing_nullable=True,
               existing_server_default=sa.Computed('(setweight(to_tsvector(\'english\'::regconfig, (COALESCE(title, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, COALESCE(description, \'\'::text)), \'B\'::"char"))', persisted=True))
    op.drop_index('ix_applications_job_id_status', table_name='job_board_applications')
    op.drop_index('ix_applications_candidate_id_job_id', table_name='job_board_applications')
    op.drop_table('job_board_applications')
    sa.Enum(name="application_status_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
