"""add field role to users

Revision ID: 4ceb1a4d7077
Revises: 38c3d6844337
Create Date: 2026-06-10 16:24:25.490289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ceb1a4d7077"
down_revision: Union[str, Sequence[str], None] = "38c3d6844337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    userrole_enum = sa.Enum("admin", "employer", "candidate", name="userrole")
    userrole_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("admin", "employer", "candidate", name="userrole"),
            nullable=False,
        ),
    )
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "role")
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
