"""add jobs_table

Revision ID: 68c47c16c50b
Revises: 2f3b3298b7cf
Create Date: 2026-07-25 08:43:41.926601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68c47c16c50b"
down_revision: Union[str, Sequence[str], None] = "2f3b3298b7cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_board_jobs",
        sa.Column(
            "title", sa.String(length=200), nullable=False, comment="Job posting title"
        ),
        sa.Column(
            "description", sa.Text(), nullable=False, comment="Full job description"
        ),
        sa.Column(
            "location", sa.String(length=255), nullable=False, comment="Job location"
        ),
        sa.Column(
            "salary_min",
            sa.Integer(),
            nullable=True,
            comment="Minimum salary in the range (nullable — either bound optional)",
        ),
        sa.Column(
            "salary_max",
            sa.Integer(),
            nullable=True,
            comment="Maximum salary in the range (nullable — either bound optional)",
        ),
        sa.Column(
            "job_type",
            sa.Enum(
                "FULL_TIME",
                "PART_TIME",
                "CONTRACT",
                "INTERNSHIP",
                "FREELANCE",
                name="job_type_enum",
            ),
            nullable=False,
            comment="Employment type of the job",
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "OPEN", "CLOSED", "ARCHIVED", name="job_status_enum"),
            nullable=False,
            comment="Lifecycle status of the job posting",
        ),
        sa.Column(
            "skills",
            postgresql.ARRAY(sa.String(length=100)),
            nullable=False,
            comment="Required skills for the job",
        ),
        sa.Column(
            "employer_id",
            sa.UUID(),
            nullable=False,
            comment="Identifier of the employer who owns this job",
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, ''))",
                persisted=True,
            ),
            nullable=True,
            comment="Full-text search vector, auto-derived from title + description",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the record",
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["employer_id"], ["job_board_users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_board_jobs")
    # ### end Alembic commands ###
